// ALTERA CRIANDO OU REMOVENDO COLUNAS EM UMA TABELA

ALTER TABLE csfloat ADD float_valor FLOAT;
ALTER TABLE csfloat DROP COLUMN float_valor;

//ALTERA O NOME DE UMA TABELA E COLUNAS
ALTER TABLE csfloat RENAME TO marketcsgo;
ALTER TABLE marketcsgo RENAME COLUMN origem TO marketplace;


//ALTERA O TIPO DE DADO
ALTER TABLE csfloat ALTER COLUMN origem TYPE INT;

//ALTERA VALOR PADRÃO DE UMA COLUNA
ALTER TABLE csfloat ALTER COLUMN origem DROP DEFAULT;
ALTER TABLE csfloat ALTER COLUMN origem SET DEFAULT;

//ALTERA VALOR NOT NULL DE UMA COLUNA
ALTER TABLE csfloat ALTER COLUMN itemid DROP NOT NULL;
ALTER TABLE csfloat ALTER COLUMN itemid SET NOT NULL;
